version: 0.0
os: linux 
files:
  - source: /
    destination: /home/ec2-user/caphe-backend
file_exists_behavior: OVERWRITE
permissions:
  - object: /home/ec2-user/caphe-backend
    owner: ec2-user
    group: ec2-user
    mode: 755
    type:
      - directory

hooks:
  # ApplicationStop:
  #   - location: /deployments/scripts/stop_app.sh
  #     timeout: 300
  #     runas: ec2-user
  ApplicationStart:
    - location: /deployments/scripts/start_app.sh
      timeout: 3000
      runas: ec2-user
