version: 0.0
os: linux 
files:
  - source: /
    destination: /
file_exists_behavior: OVERWRITE

hooks:
  ApplicationStop:
    - location: deployments/scripts/start_app.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: deployments/scripts/start_app.sh
      timeout: 3000
      runas: ec2-user
