version: 0.0
os: linux 
files:
  - source: /
    destination: /home/ec2-user/caphe-backend
file_exists_behavior: OVERWRITE

hooks:
  ApplicationStop:
    - location: /home/ec2-user/caphe-backend/deployments/scripts/start_app.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: /home/ec2-user/caphe-backend/deployments/scripts/start_app.sh
      timeout: 3000
      runas: ec2-user
